{% set name = "napari-time-series-plotter" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-time_series_plotter-{{ version }}.tar.gz
  sha256: bf08aec5222e579c44ebaccda12ecd09790f7de9639c38763da183a60a83c810

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - python >=3.8
    - matplotlib-base >=3.4.3
    - napari >=0.4.12
    - napari-plugin-engine >=0.2.0
    - numpy >=1.21.4
    - qtpy >=1.11.2

test:
  imports:
    - napari_time_series_plotter
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/ch-n/napari-time_series_plotter
  summary: A Plugin for napari to visualize pixel values over the first dimension (time -> t+3D, t+2D) as graphs.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ch-n
    - goanpeca
    - jaimergp
